### PR TITLE
fix standings table time sometimes being greater than given time

### LINKED ISSUE #150: Time over maximum time in standings table
The `formatDuration` function is supposed to take this into account but I guess there is a rounding issue or something?

Image

### PR DESCRIPTION
**Pull request by Andriamanitra**
closes #150

### CODE REVIEW

File: libs/frontend/src/lib/features/game/standings/components/standings-table.svelte [hunk 1]
```diff
@@ -40,16 +40,7 @@
...
-			game.options?.maxGameDurationInSeconds ?? DEFAULT_GAME_LENGTH_IN_SECONDS;
-		const maximumGameEndTime = gameStartTime.add(maxAllowedDurationSeconds, "s");
-
-		// determine the display end time (either submission date or max allowed end time)
-		// context: users are allowed to go over the max end time by X seconds for connection issues
-		const clampedSubmissionDate = dayjs.min(dayjs(submissionDate), maximumGameEndTime);
-
-		const gameplayDurationMs = clampedSubmissionDate.diff(gameStartTime);
-
+		const gameplayDurationMs = Math.min(dayjs(submissionDate).diff(gameStartTime), DEFAULT_GAME_LENGTH_IN_MILLISECONDS);
```
Comment (4atj) [inline libs/frontend/src/lib/features/game/standings/components/standings-table.svelte]: Fixed
```diff
- const gameplayDurationMs = Math.min(dayjs(submissionDate).diff(gameStartTime), DEFAULT_GAME_LENGTH_IN_MILLISECONDS);
+ const gameplayDurationInMs = Math.min(dayjs(submissionDate).diff(gameStartTime), DEFAULT_GAME_LENGTH_IN_MILLISECONDS);```
